### ISSUE TITLE
Platform component - Undefined when editing app files

### ISSUE THREAD

**Issue by Everlost81** [socialthrills/generator-gfp#1]
This just might be that I did something wrong when I installed the prerequisites since I think I am the only one getting it. See the attached image.
![generatorundefined](https://cloud.githubusercontent.com/assets/8389618/6264697/6dbb3e06-b826-11e4-82b5-1d600df2c993.png)

**Comment by simonauner** [comment]
Hm, strange. I'll see if I can reproduce it.

**Comment by simonauner** [comment]
Try updating your Yeoman.
