### ISSUE TITLE
Platform component - Missing line endings

### ISSUE THREAD

**Issue by Everlost81** [socialthrills/generator-gfp#3]
The template, style and readme file should have a line break added at the bottom to keep Mac happy.

**Comment by simonauner** [comment]
Will add `"end_with_newline": true` both in the project's `jsbeautify` which in time will add linebreaks to every file as I edit them, along with adding them in the templates. The option is not documented on js-beautify's README but in code.
 https://github.com/beautify-web/js-beautify/blob/master/js/lib/beautify.js#L75
